// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serverless_sample.models;

namespace awscsharp.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("user_registration.models.Person", b =>
                {
                    b.Property<byte[]>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int?>("rolecode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rolecode");

                    b.ToTable("PersonDb");
                });

            modelBuilder.Entity("user_registration.models.Role", b =>
                {
                    b.Property<int>("code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("user_registration.models.Person", b =>
                {
                    b.HasOne("user_registration.models.Role", "role")
                        .WithMany()
                        .HasForeignKey("rolecode");

                    b.Navigation("role");
                });
#pragma warning restore 612, 618
        }
    }
}
